name: Pull Request Actions

on: pull_request

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: |
          dotnet restore
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore     
      - name: Test
        run: |
          dotnet test  
      - name: Publish EF6
        run: |
          dotnet pack -c Release src/Unosquare.EntityFramework.Specification.EF6/Unosquare.EntityFramework.Specification.EF6.csproj -o .
          dotnet nuget push Unosquare.EntityFramework.Specification.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
      - name: Publish EFCore
        run: |
          dotnet pack -c Release src/Unosquare.EntityFramework.Specification.EFCore/Unosquare.EntityFramework.Specification.EFCore.csproj -o .
          dotnet nuget push Unosquare.EntityFramework.Specification.EFCore.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate